services:
  backend:
    build: .
    command: uvicorn app.src.main:app --reload
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
      - MODEL_PATH=/app/models

  frontend:
    build: .
    command: streamlit run frontend/streamlit_app.py
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    depends_on:
      - backend
    environment:
      - PYTHONPATH=/app
      - BACKEND_URL=http://backend:8000